services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-docker-volume:/var/lib/postgresql/data
    networks:
      - postgres-docker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-docker-volume:
    driver: local

networks:
  postgres-docker-network:
    driver: bridge
